FROM apache/airflow:2.11.0

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends openjdk-17-jre-headless \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

COPY airflows/requirements.txt /opt/airflow/requirements.txt

USER airflow

RUN pip install --no-cache-dir -r /opt/airflow/requirements.txt